//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUser()
        {
            this.AspNetUserExceptionLogs = new HashSet<AspNetUserExceptionLog>();
        }
    
        public string ID { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string IPAddress { get; set; }
        public string IPAddressCountry { get; set; }
        public string IPAddressCity { get; set; }
        public bool Delinquent { get; set; }
        public Nullable<decimal> LifetimeValue { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public bool DemoAccount { get; set; }
        public bool MasterAccount { get; set; }
        public bool AdminAccount { get; set; }
        public string ProfileAdminTable { get; set; }
        public string ProfileTableName { get; set; }
        public string TreasuryTableName_TBD_ { get; set; }
        public string RegistrationCode { get; set; }
        public bool ProfileUpdated { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool PhoneSMSAllowed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public System.DateTimeOffset RegistrationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserExceptionLog> AspNetUserExceptionLogs { get; set; }
        public virtual AspNetUserLoginLog AspNetUserLoginLog { get; set; }
    }
}
