//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubPhoenix_TBD_
    {
        public int ID { get; set; }
        public string AdminID { get; set; }
        public string MemberID { get; set; }
        public int ClubID { get; set; }
        public string YearTerm { get; set; }
    }
}
