//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clubs_TBD_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clubs_TBD_()
        {
            this.ClubEntityMaps = new HashSet<ClubEntityMap>();
            this.ProfileMembers = new HashSet<ProfileMember>();
        }
    
        public int ID { get; set; }
        public int DistrictID { get; set; }
        public int ClubID { get; set; }
        public string ClubPresidentID { get; set; }
        public string ClubName { get; set; }
        public Nullable<int> ClubMemberQuantity { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string ImageLink { get; set; }
        public string BackgroundColor { get; set; }
        public Nullable<System.DateTime> Founded { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubEntityMap> ClubEntityMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileMember> ProfileMembers { get; set; }
    }
}
