//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListUniversity
    {
        public int ID { get; set; }
        public Nullable<int> InstitutionID { get; set; }
        public string InstitutionName { get; set; }
        public string InstitutionAddress { get; set; }
        public string InstitutionCity { get; set; }
        public string InstitutionState { get; set; }
        public string InstitutionZipcode { get; set; }
        public string InstitutionWebAddress { get; set; }
        public string AccreditationType { get; set; }
        public string AgencyName { get; set; }
        public string ProgramName { get; set; }
        public string AccreditationStatus { get; set; }
        public string AccreditationDateType { get; set; }
        public string Periods { get; set; }
        public string LastAction { get; set; }
        public string ImageLink { get; set; }
        public Nullable<System.DateTime> Founded { get; set; }
    }
}
