//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListDistricts_TBD_
    {
        public int ID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public string DistrictPresidentID { get; set; }
        public string DistrictName { get; set; }
        public Nullable<int> DistrictMemberQuantity { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string EmailDomain { get; set; }
        public string ImageLink { get; set; }
        public string BackgroundColor { get; set; }
        public Nullable<System.DateTime> Founded { get; set; }
    }
}
