//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meeting()
        {
            this.CounterRecords = new HashSet<CounterRecord>();
            this.GrammarianRecords = new HashSet<GrammarianRecord>();
            this.GuestAttendances = new HashSet<GuestAttendance>();
            this.MeetingAwards = new HashSet<MeetingAward>();
        }
    
        public int MeetingID { get; set; }
        public string Location { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<int> TblTopic1ID { get; set; }
        public string TblTopic1Title { get; set; }
        public Nullable<int> TblTopic2ID { get; set; }
        public string TblTopic2Title { get; set; }
        public Nullable<int> TblTopic3ID { get; set; }
        public string TblTopic3Title { get; set; }
        public Nullable<int> TblTopic4ID { get; set; }
        public string TblTopic4Title { get; set; }
        public Nullable<int> TblTopic5ID { get; set; }
        public string TblTopic5Title { get; set; }
        public Nullable<int> Speaker1ID { get; set; }
        public string Speech1Title { get; set; }
        public Nullable<int> Speech1Type { get; set; }
        public Nullable<int> Speaker2ID { get; set; }
        public string Speech2Title { get; set; }
        public Nullable<int> Speech2Type { get; set; }
        public Nullable<int> Speaker3ID { get; set; }
        public string Speaker3Title { get; set; }
        public Nullable<int> Speech3Type { get; set; }
        public Nullable<int> Evaluator1ID { get; set; }
        public Nullable<int> Evaluator2ID { get; set; }
        public Nullable<int> Evaluator3ID { get; set; }
        public Nullable<int> ToastmasterID { get; set; }
        public Nullable<int> GenEvaluatorID { get; set; }
        public Nullable<int> AhCounterID { get; set; }
        public Nullable<int> GrammarianID { get; set; }
        public Nullable<int> HumoristID { get; set; }
        public string WordOfTheDay { get; set; }
        public string WordOfTheDayDef { get; set; }
        public Nullable<int> WordOfTheDayPOS { get; set; }
        public Nullable<int> BestSpeaker { get; set; }
        public Nullable<int> BestFunctionary { get; set; }
        public Nullable<int> BestTblTopic { get; set; }
        public Nullable<int> BestEvaluator { get; set; }
        public Nullable<int> MostImproved { get; set; }
        public Nullable<int> MostEnthusiastic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CounterRecord> CounterRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrammarianRecord> GrammarianRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuestAttendance> GuestAttendances { get; set; }
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual Member Member2 { get; set; }
        public virtual Member Member3 { get; set; }
        public virtual Member Member4 { get; set; }
        public virtual Member Member5 { get; set; }
        public virtual Member Member6 { get; set; }
        public virtual Member Member7 { get; set; }
        public virtual Member Member8 { get; set; }
        public virtual Member Member9 { get; set; }
        public virtual Member Member10 { get; set; }
        public virtual Member Member11 { get; set; }
        public virtual Member Member12 { get; set; }
        public virtual Member Member13 { get; set; }
        public virtual Member Member14 { get; set; }
        public virtual Member Member15 { get; set; }
        public virtual Member Member16 { get; set; }
        public virtual Member Member17 { get; set; }
        public virtual Member Member18 { get; set; }
        public virtual Member Member19 { get; set; }
        public virtual Member Member20 { get; set; }
        public virtual Member Member21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingAward> MeetingAwards { get; set; }
    }
}
