//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAward
    {
        public int AwardID { get; set; }
        public int ID { get; set; }
        public string PathCompleted { get; set; }
        public string RecognitionAward { get; set; }
        public Nullable<bool> ApplicationSubmitted { get; set; }
        public Nullable<System.DateTime> AwardDate { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
