//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toast.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<AspNetUserExceptionLog> AspNetUserExceptionLogs { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<ClubEntityMap> ClubEntityMaps { get; set; }
        public virtual DbSet<ClubPhoenix_TBD_> ClubPhoenix_TBD_ { get; set; }
        public virtual DbSet<ClubPosition> ClubPositions { get; set; }
        public virtual DbSet<Clubs_TBD_> Clubs_TBD_ { get; set; }
        public virtual DbSet<CounterRecord> CounterRecords { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<EducationAward> EducationAwards { get; set; }
        public virtual DbSet<Goal> Goals { get; set; }
        public virtual DbSet<GrammarianRecord> GrammarianRecords { get; set; }
        public virtual DbSet<GuestAttendance> GuestAttendances { get; set; }
        public virtual DbSet<ListCity> ListCities { get; set; }
        public virtual DbSet<ListCountry> ListCountries { get; set; }
        public virtual DbSet<ListDegree> ListDegrees { get; set; }
        public virtual DbSet<ListMajor> ListMajors { get; set; }
        public virtual DbSet<ListSkill> ListSkills { get; set; }
        public virtual DbSet<ListState> ListStates { get; set; }
        public virtual DbSet<ListUniversity> ListUniversities { get; set; }
        public virtual DbSet<MapConnectionUser> MapConnectionUsers { get; set; }
        public virtual DbSet<MapUser> MapUsers { get; set; }
        public virtual DbSet<Meeting> Meetings { get; set; }
        public virtual DbSet<MeetingAward> MeetingAwards { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberAward> MemberAwards { get; set; }
        public virtual DbSet<NotificationExceptionLog> NotificationExceptionLogs { get; set; }
        public virtual DbSet<NotificationsUser> NotificationsUsers { get; set; }
        public virtual DbSet<NotificationsUserType> NotificationsUserTypes { get; set; }
        public virtual DbSet<OfficerRole> OfficerRoles { get; set; }
        public virtual DbSet<ProfileAwardsMap> ProfileAwardsMaps { get; set; }
        public virtual DbSet<ProfileBusinessPosition> ProfileBusinessPositions { get; set; }
        public virtual DbSet<ProfileComment> ProfileComments { get; set; }
        public virtual DbSet<ProfileExternalNotification> ProfileExternalNotifications { get; set; }
        public virtual DbSet<ProfileExternalNotificationsType> ProfileExternalNotificationsTypes { get; set; }
        public virtual DbSet<ProfileMessage> ProfileMessages { get; set; }
        public virtual DbSet<ProfileMessageSession> ProfileMessageSessions { get; set; }
        public virtual DbSet<ProfileMessageUserSession> ProfileMessageUserSessions { get; set; }
        public virtual DbSet<ProfilePost> ProfilePosts { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<TableTopicsCategory> TableTopicsCategories { get; set; }
        public virtual DbSet<TestProfileMap> TestProfileMaps { get; set; }
        public virtual DbSet<TestProfile> TestProfiles { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<TestType> TestTypes { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserLoginLog> AspNetUserLoginLogs { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsersAttempt> AspNetUsersAttempts { get; set; }
        public virtual DbSet<ListDistricts_TBD_> ListDistricts_TBD_ { get; set; }
        public virtual DbSet<NotificationsUserMessage> NotificationsUserMessages { get; set; }
        public virtual DbSet<ProfileMember> ProfileMembers { get; set; }
    }
}
