//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationsUserMessage
    {
        public int ID { get; set; }
        public int NotificationType { get; set; }
        public string TemplateName { get; set; }
        public string Subject { get; set; }
    }
}
