//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileComment
    {
        public int ID { get; set; }
        public int ParentPostID { get; set; }
        public string MemberID { get; set; }
        public string UserName { get; set; }
        public string Message { get; set; }
        public Nullable<bool> Hidden { get; set; }
        public string ImageLink { get; set; }
        public System.DateTimeOffset DatePosted { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
