//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileMember
    {
        public string MemberID { get; set; }
        public Nullable<int> ClubID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string Skills { get; set; }
        public string UniversitiesID { get; set; }
        public string UniversitiesRegionsID { get; set; }
        public string UniversityMajorsID { get; set; }
        public string UniversityDegreesID { get; set; }
        public Nullable<int> UniversityCountryID { get; set; }
        public Nullable<int> UniversityStateID { get; set; }
        public Nullable<bool> UniversityAttending { get; set; }
        public string GraduatesID { get; set; }
        public string GraduatesRegionsID { get; set; }
        public string GraduateMajorsID { get; set; }
        public string GraduateDegreesID { get; set; }
        public Nullable<int> GraduateCountryID { get; set; }
        public Nullable<int> GraduateStateID { get; set; }
        public Nullable<bool> GraduateAttending { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<System.DateTime> UniversitySchoolGraduationDate { get; set; }
        public Nullable<System.DateTime> GraduateSchoolGraduationDate { get; set; }
        public string MyDataView { get; set; }
        public string About { get; set; }
        public string ImageLink { get; set; }
        public string BannerLink { get; set; }
        public string ProfileStatus { get; set; }
        public Nullable<System.DateTimeOffset> ProfileInactiveDate { get; set; }
        public bool TourShown { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Clubs_TBD_ Clubs_TBD_ { get; set; }
        public virtual ListCity ListCity { get; set; }
        public virtual ProfileBusinessPosition ProfileBusinessPosition { get; set; }
    }
}
