//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileMessageUserSession
    {
        public int ID { get; set; }
        public string SessionID { get; set; }
        public string UserID { get; set; }
        public bool Hidden { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ProfileMessageSession ProfileMessageSession { get; set; }
    }
}
