//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileExternalNotification
    {
        public int ID { get; set; }
        public int TestCaseID { get; set; }
        public int NotificationTypeID { get; set; }
        public string TestCase { get; set; }
        public string UserID { get; set; }
        public bool Unread { get; set; }
        public bool Processed { get; set; }
        public System.DateTimeOffset EventDate { get; set; }
    }
}
