//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toast.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProfileEntities : DbContext
    {
        public ProfileEntities()
            : base("name=ProfileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUserLoginLog> AspNetUserLoginLogs { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ProfileAwardsMap> ProfileAwardsMaps { get; set; }
        public virtual DbSet<ProfileBusinessPosition> ProfileBusinessPositions { get; set; }
        public virtual DbSet<ProfileComment> ProfileComments { get; set; }
        public virtual DbSet<ProfileExternalNotification> ProfileExternalNotifications { get; set; }
        public virtual DbSet<ProfileExternalNotificationsType> ProfileExternalNotificationsTypes { get; set; }
        public virtual DbSet<ProfileMessage> ProfileMessages { get; set; }
        public virtual DbSet<ProfileMessageSession> ProfileMessageSessions { get; set; }
        public virtual DbSet<ProfileMessageUserSession> ProfileMessageUserSessions { get; set; }
        public virtual DbSet<ProfilePost> ProfilePosts { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<ClubPosition> ClubPositions { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<ClubEntityMap> ClubEntityMaps { get; set; }
        public virtual DbSet<ProfileMember> ProfileMembers { get; set; }
        public virtual DbSet<vw_UserBasicInfo> vw_UserBasicInfo { get; set; }
    }
}
