//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileMessage
    {
        public int ID { get; set; }
        public string SessionID { get; set; }
        public string SenderID { get; set; }
        public string ReceiverID { get; set; }
        public string SenderName { get; set; }
        public string SenderImageLink { get; set; }
        public string Message { get; set; }
        public Nullable<bool> Unread { get; set; }
        public System.DateTimeOffset Date { get; set; }
    }
}
