//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestProfile
    {
        public int ID { get; set; }
        public string Profile { get; set; }
        public string ProfileDirectory { get; set; }
        public bool Available { get; set; }
    }
}
