//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int ID { get; set; }
        public string UUID { get; set; }
        public string TaskID { get; set; }
        public Nullable<int> TestTypeID { get; set; }
        public string UserID { get; set; }
        public string TestCase { get; set; }
        public string Action { get; set; }
        public string ExpectedResult { get; set; }
        public Nullable<double> ElapsedTime { get; set; }
        public string Result { get; set; }
        public string TestNote { get; set; }
        public Nullable<System.DateTimeOffset> EventDate { get; set; }
    }
}
