//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserBasicInfo
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string ProfileTableName { get; set; }
        public Nullable<bool> MasterAccount { get; set; }
        public Nullable<bool> AdminAccount { get; set; }
        public int ClubID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string ImageLink { get; set; }
        public string BannerLink { get; set; }
        public string ProfileStatus { get; set; }
        public bool TourShown { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDate { get; set; }
        public string Position { get; set; }
    }
}
